(ns projecteuler.core
  (:use projecteuler.utils))

(defn problem001 []
  "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
  The sum of these multiples is 23.
  Find the sum of all the multiples of 3 or 5 below 1000."
  (reduce + (into #{} (reduce conj (filter #(= (mod % 3) 0) (range 1000))(filter #(= (mod % 5) 0) (range 1000))))))

(defn problem002 []
  "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
  (reduce + (filter even? (take-while #(< % 4e6) fibs))))

(defn problem003 [number]
  "The prime factors of 13195 are 5, 7, 13 and 29.
   What is the largest prime factor of the number 600851475143?"
  (loop [sequence (reverse (filter prime? (range 2 (Math/sqrt number))))]
    (if (= 0 (mod number (first sequence)))
      (first sequence)
      (recur (rest sequence)))))

(defn problem004 []
  "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
  Find the largest palindrome made from the product of two 3-digit numbers."
  (apply max
         (for [x (range 100 999)
               y (range 100 999)
               :when (palindrome? (* x y))]
           (* x y))))

(defn problem005 []
  "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
  What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?"
  (first (filter (fn [n] (every? #(zero? (rem n %)) (range 2 21))) (iterate inc 1))))

(defn problem006 [n]
  "The sum of the squares of the first ten natural numbers is,
  12 + 22 + ... + 102 = 385
  The square of the sum of the first ten natural numbers is,
  (1 + 2 + ... + 10)2 = 552 = 3025
  Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.
  Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum."
  (- (square-of-sum n) (sum-of-squares n)))

(defn problem007 [n]
  "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
  What is the 10 001st prime number?"
  (nth  (filter prime? (range)) (- n 1) ))

(defn problem010 [n]
  "The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
  Find the sum of all the primes below two million."
  (reduce + (filter prime? (range n))))

(defn problem015 []
  "Starting in the top left corner of a 2×2 grid, there are 6 routes (without backtracking) to the bottom right corner.
  How many routes are there through a 20×20 grid?"
  (grid-combinations 20 20))

(defn problem020 [n]
  "n! means n × (n − 1) × ... × 3 × 2 × 1
  For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
  and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.
  Find the sum of the digits in the number 100!"
  (sum-digits (str (factorial n))))
