(ns projecteuler.core
  (:use projecteuler.utils)
  (:use clojure.contrib.math)
  (:use [clojure.contrib.seq-utils :only [find-first indexed] ])
  )

(defn problem001 []
  "If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
  The sum of these multiples is 23.
  Find the sum of all the multiples of 3 or 5 below 1000."
  (reduce + (into #{} (reduce conj (filter #(= (mod % 3) 0) (range 1000))(filter #(= (mod % 5) 0) (range 1000))))))

(defn problem002 []
  "Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."
  (reduce + (filter even? (take-while #(< % 4e6) fibs))))

(defn problem003 [number]
  "The prime factors of 13195 are 5, 7, 13 and 29.
   What is the largest prime factor of the number 600851475143?"
  (loop [sequence (reverse (filter prime? (range 2 (Math/sqrt number))))]
    (if (= 0 (mod number (first sequence)))
      (first sequence)
      (recur (rest sequence)))))

(defn problem004 []
  "A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.
  Find the largest palindrome made from the product of two 3-digit numbers."
  (apply max
         (for [x (range 100 999)
               y (range 100 999)
               :when (palindrome? (* x y))]
           (* x y))))

(defn problem005 []
  "2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.
  What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?"
  (first (filter (fn [n] (every? #(zero? (rem n %)) (range 2 21))) (iterate inc 1))))

(defn problem006 [n]
  "The sum of the squares of the first ten natural numbers is,
  12 + 22 + ... + 102 = 385
  The square of the sum of the first ten natural numbers is,
  (1 + 2 + ... + 10)2 = 552 = 3025
  Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is 3025 − 385 = 2640.
  Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum."
  (- (square-of-sum n) (sum-of-squares n)))

(defn problem007 [n]
  "By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13.
  What is the 10 001st prime number?"
  (nth  (filter prime? (range)) (- n 1) ))

(defn problem008 [s]
  "Find the greatest product of five consecutive digits in the 1000-digit number. (see Test)"
  (def number-list (num-string-to-list-nums s))
  (apply max (convert-list number-list * 5)))

(defn problem009 [x]
  "A Pythagorean triplet is a set of three natural numbers, a < b < c, for which,
   a2 + b2 = c2
   For example, 32 + 42 = 9 + 16 = 25 = 52.
   There exists exactly one Pythagorean triplet for which a + b + c = 1000.
   Find the product abc."
  (first (for [a (range 1 x)
               b (range a x)
               c [(max 0 (- x a b))]
               :when (= (* c c) (+ (* a a) (* b b)))]
           (* a b c))))

(defn problem010 [n]
  "The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
  Find the sum of all the primes below two million."
  (reduce + (filter prime? (range n))))

(defn problem012 []
  "What is the value of the first triangle number to have over five hundred divisors?"
  (first (drop-while #(<= (num-of-divisors %) 500) triangles))
  )

(defn problem015 []
  "Starting in the top left corner of a 2×2 grid, there are 6 routes (without backtracking) to the bottom right corner.
  How many routes are there through a 20×20 grid?"
  (grid-combinations 20 20))

(defn problem016 []
  "215 = 32768 and the sum of its digits is 3 + 2 + 7 + 6 + 8 = 26.
   What is the sum of the digits of the number 2 ^ 1000"
  (sum-digits (str (.pow (BigInteger. "2") 1000)))
  )

(defn problem020 [n]
  "n! means n × (n − 1) × ... × 3 × 2 × 1
  For example, 10! = 10 × 9 × ... × 3 × 2 × 1 = 3628800,
  and the sum of the digits in the number 10! is 3 + 6 + 2 + 8 + 8 + 0 + 0 = 27.
  Find the sum of the digits in the number 100!"
  (sum-digits (str (factorial n))))

(defn problem021 []
  "Let d(n) be defined as the sum of proper divisors of n (numbers less than n which divide evenly into n).
   If d(a) = b and d(b) = a, where a ≠ b, then a and b are an amicable pair and each of a and b are called amicable numbers.
   For example, the proper divisors of 220 are 1, 2, 4, 5, 10, 11, 20, 22, 44, 55 and 110; therefore d(220) = 284. The proper divisors of 284 are 1, 2, 4, 71 and 142; so d(284) = 220.
   Evaluate the sum of all the amicable numbers under 10000."
  (reduce + (filter amicable? (range 2 10000))))

(defn problem025 []
  "The Fibonacci sequence is defined by the recurrence relation:
   Fn = Fn−1 + Fn−2, where F1 = 1 and F2 = 1.

   The 12th term, F12, is the first term to contain three digits.
   F12 = 144
   What is the first term in the Fibonacci sequence to contain 1000 digits?"
  (first (find-first #(>= (count (str (second %))) 1000) (indexed fibs))) )

(defn problem036 []
  "The decimal number, 585 = 10010010012 (binary), is palindromic in both bases.
   Find the sum of all numbers, less than one million, which are palindromic in base 10 and base 2.
   (Please note that the palindromic number, in either base, may not include leading zeros.)"
  (reduce + (filter #(palindrome-base10-and-base2? %) (range 1000000))))


(defn problem048 [n]
  "The series, 1^1 + 2^2 + 3^3 + ... + 10^10 = 10405071317.
   Find the last ten digits of the series, 1^1 + 2^2 + 3^3 + ... + 1000^1000."
  (apply str (reverse (take 10 (reverse
                                (str (reduce + (map #(.pow (BigInteger. (str %)) %) (range 1 (inc n))))))))))

(defn problem049 []
  "The arithmetic sequence, 1487, 4817, 8147, in which each of the terms increases by 3330, is unusual in two ways: (i) each of the three terms are prime, and, (ii) each of the 4-digit numbers are permutations of one another.
   There are no arithmetic sequences made up of three 1-, 2-, or 3-digit primes, exhibiting this property, but there is one other 4-digit increasing sequence.
   What 12-digit number do you form by concatenating the three terms in this sequence?"
  (first
   (for [x (filter prime? (range 2000 3000))
         y (filter prime? (range 6000 7000))
         z (filter prime? (range 9000 9999))
         :when (cond
                (not= x y z) (cond
                              (= (sort (str x)) (sort (str y)) (sort (str z))) (= (- y x) (- z y))
                              :else false)
                :else false)]
     [x y z])))

(defn problem052 []
  "It can be seen that the number, 125874, and its double, 251748, contain exactly the same digits, but in a different order.
   Find the smallest positive integer, x, such that 2x, 3x, 4x, 5x, and 6x, contain the same digits."
  (first (for [x (range 1 99999999999999999)
               :let [ onex  (sort (str x))
                     twox   (sort (str (* x 2)))
                     threex (sort (str (* x 3)))
                     fourx  (sort (str (* x 4)))
                     fivex  (sort (str (* x 5)))
                     sixx   (sort (str (* x 6)))]
               :when (= onex twox threex fourx fivex sixx)]
           x)))
